### ISSUE TITLE
unable to execute SmartStitch on Mac

### ISSUE THREAD

**Issue by wander3010** [MechTechnology/SmartStitch#7]
hello, I'm unable to execute SmartStitch on MacBook even though I followed the instructions. here's the error message I encountered in the command prompt.
-----
```
wander@Wanders-MacBook-Pro smartstitch-2.3.1 % python smartstitchgui.py
Traceback (most recent call last):
  File "smartstitchgui.py", line 9, in <module>
    import SmartStitchCore as ssc
  File "/Users/wander/Documents/SmartStitch-2.3.1/SmartStitchCore.py", line 142
    image.save(new_folder + '/' + str(f'{imageIndex:02}') + outputformat, quality=100)
                                                       ^
SyntaxError: invalid syntax
```
-----
able to help? thank you! (I used SmartStitch on windows too and it's very easy to use, but that's an old laptop and its prone to hanging on me so I would want to install on mac too. many thanks!

**Comment by MechTechnology** [comment]
Sadly I never tested it on a mac myself, but i will find a friend and look for a solution, but expect to wait a bit.

**Comment by Aeonss** [comment]
> 

Update your version of python

**Comment by wander3010** [comment]
`wander@wanders-MacBook-Pro SmartStitch-2.3.1 % python3 SmartStitchGUI.py
Traceback (most recent call last):
  File "/Users/wander/Downloads/SmartStitch-2.3.1/SmartStitchGUI.py", line 489, in <module>
    SmartStitchGUI().mainloop()
  File "/Users/wander/Downloads/SmartStitch-2.3.1/SmartStitchGUI.py", line 23, in __init__
    self.show_advanced_settings = BooleanVar(False)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tkinter/__init__.py", line 610, in __init__
    Variable.__init__(self, master, value, name)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tkinter/__init__.py", line 372, in __init__
    self._root = master._root()
AttributeError: 'bool' object has no attribute '_root'
wander@wanders-MacBook-Pro SmartStitch-2.3.1 % `

I got this error after trying to execute it

**Comment by AbhiMayadam** [comment]
> `wander@wanders-MacBook-Pro SmartStitch-2.3.1 % python3 SmartStitchGUI.py Traceback (most recent call last): File "/Users/wander/Downloads/SmartStitch-2.3.1/SmartStitchGUI.py", line 489, in <module> SmartStitchGUI().mainloop() File "/Users/wander/Downloads/SmartStitch-2.3.1/SmartStitchGUI.py", line 23, in __init__ self.show_advanced_settings = BooleanVar(False) File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tkinter/__init__.py", line 610, in __init__ Variable.__init__(self, master, value, name) File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tkinter/__init__.py", line 372, in __init__ self._root = master._root() AttributeError: 'bool' object has no attribute '_root' wander@wanders-MacBook-Pro SmartStitch-2.3.1 % `
> 
> I got this error after trying to execute it after updating my python

I never checked this but SmartStitch doesnt run on 3.10, but it will urn on 3.9. I would downgrade.

**Comment by MechTechnology** [comment]
The new version I am working on the dev branch is running 3.10,2, so this issue should be solved, and hopefully I will also move to QT for the frontend, so the experience for mac users will drastically change

- I will keep this issue open until the new version is ready and out.

**Comment by MechTechnology** [comment]
V3 is now officially out if the problem still exists with it, please open a new issue
